In [142]:
import requests

In [143]:
from urllib.request import Request, urlopen
from bs4 import BeautifulSoup as soup

In [144]:
url = "https://www.thefork.fr/api/search/restaurants?query%5Bplace%5D%5Btype%5D=near_city&query%5Bplace%5D%5Bvalue%5D%5BcityId%5D=415144&query%5BdecorateRestaurantTags%5D%5B0%5D=4427&result%5BcurrentScreen%5D=SEARCH_RESULT_PAGE&result%5Babtest%5D%5BdisplaySnippets%5D=true&filter%5BrestaurantTagIdList%5D%5B0%5D%5Btags%5D%5B0%5D=4427&filter%5BoriginCodeList%5D%5B0%5D=THEFORKMANAGER&page%5Bnumber%5D=2&page%5Bsize%5D=25"

In [145]:
headers = """accept: application/json
accept-encoding: gzip, deflate, br
accept-language: fr-FR
cache-control: no-cache
content-type: application/json
cookie: tf_abtests_freshness=true; tf_ab_test=booking_funnel%3Dcontrol; CC=15102-e75; connected=false; G_ENABLED_IDPS=google; trackingId=7fb17de9-e38d-4694-977e-acf10f7f2730; _evidon_consent_cookie={"consent_date":"2020-11-26T13:49:11.189Z","consent_type":1}; ry_ry-l4f02rfr_realytics=eyJpZCI6InJ5XzRBQzc2MzIzLTYyNDAtNDNCQy04ODk4LTREMUNBNkI5N0Q3NyIsImNpZCI6bnVsbCwiZXhwIjoxNjM3OTM0NTUxNDEyLCJjcyI6bnVsbH0%3D; _gid=GA1.2.1785263786.1606398551; _hjTLDTest=1; _hjid=93a91613-4ab6-4b7d-be0b-a9e86f70b513; _hjIncludedInPageviewSample=1; _uetsid=332c86602fee11eba9e23b2c8292b73b; _uetvid=332cdfd02fee11ebb06231a0e51c1fb8; _fbp=fb.1.1606398567241.1268821727; _hjAbsoluteSessionInProgress=0; _gat=1; _dc_gtm_UA-153529018-5=1; _gat_UA-153529018-5=1; _ga_7NBMPFZNBS=GS1.1.1606401925.2.1.1606401932.0; _ga=GA1.1.792505627.1606398551; datadome=2ZnNflQjZ5jJh~vEBmBZygkTKDFNT~x_IEgOfZN9DybdaN2ksMpx2_tSv8SIEQN0bKpN_nM0VNUFyWmrup~nf3XxnkV08GJPT5IF9AFRxx
pragma: no-cache
referer: https://www.thefork.fr/search/?cityId=415144&restaurantTagId[]=4427&p=2
sec-fetch-dest: empty
sec-fetch-mode: cors
sec-fetch-site: same-origin
timezone: Europe/Paris
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36"""

In [244]:
headers = dict([i.split(': ') for i in headers.split('\n')])
response = requests.get(url = url, headers = headers)
data = response.json()

AttributeError: 'dict' object has no attribute 'split'

In [245]:
import pandas as pd

In [246]:
data = data['data']

TypeError: list indices must be integers or slices, not str

In [263]:
pd.json_normalize(data)
#data 
!git

,name,servesCuisine,priceRange,currenciesAccepted,mainPhotoSrc,hasLoyaltyProgram,isBookable,isInsider,uuid,canBurnYums,...,marketingOffer.title,marketingOffer.type,bestOffer.tagsIds,bestOffer.id,bestOffer.label,bestOffer.name,yumsDetail.isSuperYums,yumsDetail.description,yumsDetail.yumsCount,marketingOffer
0,Enza & Famiglia Pizze e Vino,Italien,34,EUR,https://res.cloudinary.com/tf-lab/image/upload...,True,True,False,9ff2872a-c0f9-4102-bac4-356c597bcc28,True,...,-30% sur la carte,None,[],4273329,-30%,-30% sur la carte,False,NaN,NaN,NaN
1,New Sakura,Japonais,23,EUR,https://res.cloudinary.com/tf-lab/image/upload...,False,True,False,d820e2c0-bc49-4719-8f53-11674acdd83b,False,...,-30% sur la carte,None,[],4250673,-30%,-30% sur la carte,False,NaN,NaN,NaN
2,Ristorante Prima,Italien,26,EUR,https://res.cloudinary.com/tf-lab/image/upload...,False,True,False,88d430e6-de46-4eeb-b8c9-a45f3fe20dcd,False,...,-20% sur la carte,None,[],4243657,-20%,-20% sur la carte,False,NaN,NaN,NaN
3,Les Bariolés de Maud,Français,22,EUR,https://res.cloudinary.com/tf-lab/image/upload...,True,True,False,2ab9667a-b52c-4ed6-a66d-be0d7867287c,False,...,Dîner d'automne 26 €,None,[3],4233723,MENU,Dîner d'automne 26 €,True,YUMS x2,0.0,NaN
4,L'Epopée,Français,33,EUR,https://res.cloudinary.com/tf-lab/image/upload...,False,True,False,14526dbe-0bba-4dc0-8b0a-d03ba2083200,False,...,-30% sur la carte,None,[],4241223,-30%,-30% sur la carte,False,NaN,NaN,NaN
5,Au Bon Moment Comme à la Maison,Marocain,26,EUR,https://res.cloudinary.com/tf-lab/image/upload...,False,True,False,63f6f58d-648a-4db1-a5d0-83e57db111d3,False,...,-30% sur la carte,None,[],4210579,-30%,-30% sur la carte,False,NaN,NaN,NaN
6,Neelkanth,Indien,22,EUR,https://res.cloudinary.com/tf-lab/image/upload...,False,True,False,a350a63a-a22d-4307-9201-4e390c82a849,False,...,-20% sur la carte,None,[],4172023,-20%,-20% sur la carte,False,NaN,NaN,NaN
7,Les Comédiens,Pizzeria,42,EUR,https://res.cloudinary.com/tf-lab/image/upload...,False,True,False,73d2cc36-f59b-47fa-87bf-685c3fa2d6dc,False,...,-30% sur la carte,None,[],4161463,-30%,-30% sur la carte,False,NaN,NaN,NaN
8,Tassinca,Corse,15,EUR,https://res.cloudinary.com/tf-lab/image/upload...,False,True,False,774bf0ef-7f3c-4d23-a6b0-e428a48ef9f7,False,...,-20% sur la carte,None,[],4214779,-20%,-20% sur la carte,False,NaN,NaN,NaN
9,Jabal Liban,Libanais,20,EUR,https://res.cloudinary.com/tf-lab/image/upload...,False,True,False,b75507a6-fb1b-46a5-96ac-118a8ac33479,False,...,-50% sur la carte,None,[],4158507,-50%,-50% sur la carte,False,NaN,NaN,NaN
10,Dulcinea,Pizzeria,29,EUR,https://res.cloudinary.com/tf-lab/image/upload...,False,True,False,151141d5-6e92-4257-9d3b-70f22cb2545c,False,...,-30% sur la carte,None,[],4246765,-30%,-30% sur la carte,False,NaN,NaN,NaN
11,Enza & Famiglia Trattoria Saint Honoré,Italien,39,EUR,https://res.cloudinary.com/tf-lab/image/upload...,False,True,False,28f8fdd8-9b2e-4c85-9ae7-b5d08b8963ef,False,...,-30% sur la carte,None,[],4209933,-30%,-30% sur la carte,False,NaN,NaN,NaN
12,Vin et Marée Voltaire-Nation,Français,49,EUR,https://res.cloudinary.com/tf-lab/image/upload...,False,True,False,20a4b193-d100-4f78-847f-dac4cb8e9938,False,...,-30% sur la carte,None,[],4242307,-30%,-30% sur la carte,False,NaN,NaN,NaN
13,Osaka,Japonais,25,EUR,https://res.cloudinary.com/tf-lab/image/upload...,True,True,False,b9f3c232-aeab-4236-bcfa-214a22941878,False,...,NaN,NaN,[],3886235,,Stock hors promo,True,YUMS x2,0.0,NaN
14,Le Trousseau d’Or,De marché,22,EUR,https://res.cloudinary.com/tf-lab/image/upload...,True,True,False,0cf63f5f-99df-42bf-8144-2435da85de88,False,...,Formule Déjeuner en semaine €15.90,None,[13],3643711,MENU,Formule Déjeuner en semaine €15.90,True,YUMS x2,0.0,NaN
15,Imperial Treasure,Chinois,100,EUR,https://res.cloudinary.com/tf-lab/image/upload...,False,True,True,733ee62a-47c6-42f7-9572-4f39e4bec2f8,False,...,-20% sur la carte,None,[],4275419,-20%,-20% sur la carte,False,NaN,NaN,NaN
16,Matsuyama,Japonais,22,EUR,https://res.cloudinary.com/tf-lab/image/upload...,False,True,False,48344747-7bfa-4df9-a248-a377a8e16af4,False,...,-30% sur la carte,None,[],4063899,-30%,-30% sur la carte,False,NaN,NaN,NaN
17,So'Chick,Français,31,EUR,https://res.cloudinary.com/tf-lab/image/upload...,False,True,False,4ffc66f2-4012-455a-9662-33081047a0d8,False,...,-30% sur la carte,Event,"[12, 77]",2694543,MENU,-30% sur la carte,False,NaN,NaN,NaN
18,Au Petit Marguery - Rive Droite,Français,44,EUR,https://res.cloudinary.com/tf-lab/image/upload...,True,True,False,076d37e2-babc-476f-900d-ff515d6f1924,True,...,-30% sur la carte,None,[],4271613,-30%,-30% sur la carte,False,NaN,NaN,NaN
19,Alliance,Français,156,EUR,https://res.cloudinary.com/tf-lab/image/upload...,True,True,True,781aca47-ffa1-483b-9679-aa35e34d2ad3,True,...,Menu Instant déjeuner 55 €,None,[3],4262557,MENU,Menu Instant déjeuner 55 €,False,NaN,NaN,NaN
20,Curry Villa,Indien,20,EUR,https://res.cloudinary.com/tf-lab/image/upload...,False,True,False,50a23052-72d1-495a-b927-1a5dab14ab8e,False,...,-50% sur la carte,None,[],4210157,-50%,-50% sur la carte,False,NaN,NaN,NaN
21,Les Vignes du Liban,Libanais,28,EUR,https://res.cloudinary.com/tf-lab/image/upload...,False,True,False,ef91fec5-ebdf-4bc4-b1ae-47857696f3b9,False,...,-30% sur la carte,None,[113],1978569,-30%,-30% sur la carte,False,NaN,NaN,NaN
22,Mount Everest,Indien,20,EUR,https://res.cloudinary.com/tf-lab/image/upload...,False,True,False,be1ea29f-504f-405a-a95d-8a93e5cdcf4a,False,...,-40% sur la carte,None,[],3018409,-40%,-40% sur la carte,False,NaN,NaN,NaN
23,Vietnamfood,Vietnamien,30,EUR,https://res.cloudinary.com/tf-lab/image/upload...,True,True,False,3401900e-896a-4408-ad08-55414a33cec6,True,...,-50% sur la carte,None,[],4198725,-50%,-50% sur la carte,False,NaN,NaN,NaN
24,Palais de Krishnaa,Indien,25,EUR,https://res.cloudinary.com/tf-lab/image/upload...,True,True,False,a2e699cd-c155-4880-82bb-017cfcf0de13,True,...,-20% sur la carte,None,[],4003143,-20%,-20% sur la carte,False,NaN,NaN,NaN

In [255]:
FIELDS = ['name', 'priceRange', 'servesCuisine']
def clean_data(data):
    table = pd.DataFrame()
    for i in range(len(data) - 1):
        df = pd.json_normalize(data[i + 1])
        df = df[FIELDS]
        table = table.append(df)
    return table

cleand = clean_data(data)
cleand.shape
# problematic : 'address' , 'aggregateRatings', bestOffer

(24, 3)

In [249]:
addresse = [resto.get("address") for resto in data]
ad_street = [resto.get("street") for resto in addresse]
ad_quartier = [resto.get("postalCode")[-2:] for resto in addresse]

In [250]:
aggregateRatings = [resto.get("aggregateRatings") for resto in data]
aggregateRatings = [resto.get("thefork") for resto in aggregateRatings]
aggregateRatings = [sum(resto.values()) for resto in aggregateRatings]

In [251]:
bestOffer = [resto.get("bestOffer") for resto in data]
bestOffer = [resto.get("label").
             replace("%", "").
             replace("-", "")
             for resto in bestOffer]
len(bestOffer)
bestOffer

['30',
 '30',
 '20',
 'MENU',
 '30',
 '30',
 '20',
 '30',
 '20',
 '50',
 '30',
 '30',
 '30',
 '',
 'MENU',
 '20',
 '30',
 'MENU',
 '30',
 'MENU',
 '50',
 '30',
 '40',
 '50',
 '20']

In [261]:
#cleand['bestOffer'] = bestOffer 
#len(aggregateRatings)
#cleand['aggregateRatings'] = aggregateRatings

[30,
 221.7,
 262.1,
 594.3,
 987.8,
 605.5,
 311.8,
 1905.5,
 14,
 49.9,
 1492.4,
 44.4,
 12406.7,
 12.7,
 380.6,
 199.6,
 47.6,
 1358.1,
 4563.7,
 556.8,
 498.3,
 3684.4,
 2603.3,
 365.3,
 1357.4]

In [172]:
cleand

                                     name  priceRange servesCuisine
0                              New Sakura          23      Japonais
0                        Ristorante Prima          26       Italien
0                    Les Bariolés de Maud          22      Français
0                                L'Epopée          33      Français
0         Au Bon Moment Comme à la Maison          26      Marocain
0                               Neelkanth          22        Indien
0                           Les Comédiens          42      Pizzeria
0                                Tassinca          15         Corse
0                             Jabal Liban          20      Libanais
0                                Dulcinea          29      Pizzeria
0  Enza & Famiglia Trattoria Saint Honoré          39       Italien
0           Vin et Marée  Voltaire-Nation          49      Français
0                                   Osaka          25      Japonais
0                       Le Trousseau d’Or          22     De marché
0                       Imperial Treasure         100       Chinois
0                               Matsuyama          22      Japonais
0                                So'Chick          31      Français
0         Au Petit Marguery - Rive Droite          44      Français
0                                Alliance         156      Français
0                             Curry Villa          20        Indien
0                     Les Vignes du Liban          28      Libanais
0                           Mount Everest          20        Indien
0                             Vietnamfood          30    Vietnamien
0                      Palais de Krishnaa          25        Indien